### ISSUE TITLE
Just to be sure to understand

### ISSUE THREAD

**Issue by ScreamZ** [colyseus/timer#21]
Hi,

I'm exploring the Colyseus codebase, just to be sure to understand.

This library's purpose is to limit the amount of native `setInterval` inside the Server code and have something that calls all callbacks that would have been in a wild `setInterval` inside the same interval.

This way the `tick` is called on `setInterval` basis (optimally one setInterval within the whole server code, but in colyseus its in patch rate or simulation interval -> the fastest that occurs).

Also if we want to optimize, we can call `tick` method whenever we want to check if some interval can be played within the same event loop tick ? Is it?

If I understand correctly, that's DAMN smart. Good job !

**Comment by endel** [comment]
Hi @ScreamZ, 

Thanks for checking the sources and for the kind words. The main reason for having the intervals and timeouts in a single place is to allow clearing them when the room they belong to is destroyed. 

Intervals and timeouts can be the source of memory leaks, and it is too easy to forget to clear them, so this module is more about convenience than performance. 

You may be right that having too many `setInterval`'s could be bad for performance, would love to see if there's any studies about this.

Cheers!

**Comment by ScreamZ** [comment]
I think it's also more performant because you can trigger a tick (possibly) in a long-running job, which makes it even longer (ahah) but allows you to play eventual interval-based effects. I know this is a bad practice to have long-running job in the single-threaded queue but that's nice to know.

Also this lib can also solve eventual Event loop latency issue as described in this article, less timers, less chance they don't take priority https://medium.com/nodejsmadeeasy/nodejs-event-loop-lag-5d5928fd03c
