### ISSUE TITLE
Performance improvement test

### ISSUE THREAD

**Issue by ScreamZ** [colyseus/timer#22]
Hi @endel ,

I'm using your wonderful library in a project of mine based on state synchronization for an escape room in Montpellier, France.

I'm happy with it but i was asking myself what if we use a `Set` instead of a plain array ? Could this improve performances ?

https://github.com/colyseus/timer/blob/d723ee2d80cce4723e434fddf537c5d890b6c4a9/src/ClockTimer.ts#L24
https://github.com/colyseus/timer/blob/d723ee2d80cce4723e434fddf537c5d890b6c4a9/src/ClockTimer.ts#L5

Here some benchmarks 

https://www.geeksforgeeks.org/set-vs-array-in-javascript/
https://stackoverflow.com/a/39010462/5320409

What do you think ? Changes would be minor

**Comment by ScreamZ** [comment]
@endel And about this one, do you see any issue about it ? I can share a PR for both.

**Comment by endel** [comment]
Hi @ScreamZ, that's so cool, I'm happy to know you're using this project for such experience 💖

I think speed of iteration is more important than speed of removing the items, as iterating over the items (tick) happens more frequently than removing items. I appreciate the intention but I imho this would not improve overall performance
