### ISSUE TITLE
Adding promise syntax

### ISSUE THREAD

**Issue by ScreamZ** [colyseus/timer#23]
Hello @endel 

I've made some test improving the library this way:

```ts
export class Clock extends BaseClock {
  /**
   * Return a promise that resolves after the duration
   * @param duration in ms
   * @returns
   * TODO: Add some mecanism to avoid dead promise if time get destructed
   */
  duration = (duration: number) => new Promise((resolve) => this.setTimeout(resolve, duration));
}
```

This works well and allow to use the syntax

```ts
await clock.duration(10000)
console.log("Hello");
```

The issue might rise when the `Clock.clear` method is invoked as the timer get never removed and therefore the promise never resolves. This results in a memory leak? While its edge-case.

As far as i can see this could be solved by overriding the `clear` function to send an abort signal like resolving the promise with `{"cancelled": true}` and therefore in the `duration` function make a no-op.

Why would i need a `await` syntax ? Because I'm chaining animations for a real-life experience (escape room) and I want to be able to avoid callback hell.

like writing this code

```ts
async function walkStepsEffect({ setDeviceState, clock }: Controls) {
  setDeviceState({ stepperState: StepperState.One });
  await clock.duration(250);
  setDeviceState({ stepperState: StepperState.Two });
  await clock.duration(250);
  setDeviceState({ stepperState: StepperState.Three });
  await clock.duration(250);
  setDeviceState({ stepperState: StepperState.Done });
}
```

Do you have any other ideas? I can work on a pull request.

**Comment by endel** [comment]
Hi @ScreamZ, thanks for your message - that would be a nice addition. If cleared we could make the promise reject. Perhaps we could add another Delayed type that is `Type.Async` to allow this. A PR would be very welcome! Cheers
